Created the product model and added it as a dbset to the congo context.
Code2Gether-Discord/Congo pull request #22
Opened 2021-09-29 16:42 UTC by IliaIliev94

2021-09-29 18:06 UTC, ThorstenSauter commented
Should we generate the value of the `Id` property in C# or have the database provide it automatically, like it already would by default (according to the [docs](https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations#primary-keys))?

This would result in the following change:
```diff
[Key]
- public string Id { get; init; } = Guid.NewGuid().ToString();
+ public string Id { get; set; }
```

2021-09-29 18:18 UTC, IliaIliev94 commented
> Should we generate the value of the `Id` property in C# or have the database provide it automatically, like it already would by default (according to the [docs](https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations#primary-keys))?
> 
> This would result in the following change:
> ```diff
> [Key]
> - public string Id { get; init; } = Guid.NewGuid().ToString();
> + public string Id { get; set; }
> ```

I made it using a Guid, because if the Id is randomly generated every time it would be harder for users to get to a product page by just changing the Id parameter in the url (like changing /products/1 to products/2 in the url), which is sometimes an unwanted side effect. If the other members decide that we should use an Id automatically provided by the database, then I can change it.

2021-09-29 18:25 UTC, ThorstenSauter commented
Ah, that's my bad for not paying attention to the actual type of `Id`. I just assumed it was `Guid` from the initial value. I support using a `Guid` for the `Id`, but if we actually use `Guid` as the type, the database can generate it, as I alluded to earlier.
This time hopefully correct:
```diff
- public string Id { get; init; } = Guid.NewGuid().ToString();
+ public Guid Id { get; set; }
```

2021-09-29 18:51 UTC, pobiega requested changes

2021-09-29 18:51 UTC, pobiega commented on src/Congo.WebApi/Data/CongoContext.cs
> +        public DbSet<Product> Products { get; set; }
I think we should follow standard C# structure here, which would be to put properties below the constructor.

2021-09-29 18:51 UTC, pobiega commented on src/Congo.WebApi/Data/Models/Product.cs
> +        public string Id { get; init; } = Guid.NewGuid().ToString();
Agree with Thorsten, if we want Guid style IDs, this should be `Guid` prop, not a string. My only gripe with them is that they are very long and take up a lot of URL space, so an alternative worth considering is the "YouTube" style URL-safe base64 IDs. Doable, but perhaps overkill.

I will not die on this hill, so unless you feel very strongly about making a YouTube style identifier, Guid is fine.

2021-09-29 18:51 UTC, pobiega commented on src/Congo.WebApi/Data/Models/Product.cs
> +        [Required]
I'm not a big fan of `DataAnnotations` to be honest. If the desired result is to make this not nullable, I suggest we use `IEntityTypeConfiguration<T>` instead. Here is the doc page: https://docs.microsoft.com/en-us/ef/core/modeling/

It keeps the domain object pure and more POCO, and keeps the database-specific stuff away from it.

This goes for `[Key]` as well, of course.

2021-09-30 04:33 UTC, pobiega requested changes

2021-09-30 04:33 UTC, pobiega commented on src/Congo.WebApi/Data/CongoContext.cs
> +            new ProductEntityTypeConfiguration().Configure(modelBuilder.Entity<Product>());
Can we use the assembly scanning version instead here? That way we don't need to explicitly add another entry for each configuration we set up.

```csharp
modelBuilder.ApplyConfigurationsFromAssembly(typeof(CongoContext).Assembly);
```

2021-09-30 05:35 UTC, pobiega approved these changes

2021-09-30 05:54 UTC, merged