Added CartService
Code2Gether-Discord/Congo pull request #96
Opened 2021-11-29 12:54 UTC by henry-js

Mostly boilerplate atm. Not sure where I should be getting the cart Guid from

2021-11-29 13:30 UTC, pobiega commented
If you call the "add to cart" endpoint without a cart ID, it will create a new cart and give you the ID. You then reuse that ID when adding more things and to check out.

2021-11-29 20:46 UTC, henry-js commented
Pretty sure it's working as intended now, but calling the endpoint with no guid causes a null reference exception, so perhaps the get cart api endpoint isn't implemented fully yet?

2021-11-30 08:58 UTC, pobiega commented
> calling the endpoint with no guid causes a null reference exception

What endpoint are you calling? `GetCart` doesn't generate a new cart, `AddToCart` does :)

2021-12-02 21:56 UTC, valincius requested changes

2021-12-02 21:56 UTC, valincius commented on src/Congo.RazorPages/Services/ICartService.cs
> +        Task<CartResponse> GetCart(Guid? cartId = null);
Should not be nullable

2021-12-02 21:56 UTC, valincius commented on src/Congo.RazorPages/Services/CartService.cs
> +        public async Task<CartResponse> GetCart(Guid? cartId)
Should not be nullable

2021-12-02 21:56 UTC, valincius commented on src/Congo.RazorPages/Pages/Cart.cshtml.cs
> +                Response.Cookies.Append("cartId", cartId);
This isn't right, `GetCart` returns a `CartResponse` - if a `cartId` doesn't exist in the cookie then you should show a message like 'No items' or something.

You're sorta on the right track, we want this sort of logic for add to cart, but not here.

2021-12-02 21:56 UTC, valincius commented on src/Congo.RazorPages/Pages/Cart.cshtml
> +        @foreach (var cartItem in Model.Cart.CartItems)
Show a message if we have no items in our cart - or if we don't have a cart

2021-12-02 21:56 UTC, valincius commented on src/Congo.Contracts/Clients/ICongoUserClient.cs
> +        Task<ApiResponse<CartResponse>> GetCart(Guid? id);
Id should not be nullable

2021-12-02 21:56 UTC, valincius commented on src/Congo.RazorPages/Pages/Cart.cshtml.cs
> +                Response.Cookies.Append("cartId", cartId);
Need to catch error if we somehow have an invalid cart id

2021-12-02 21:57 UTC, valincius commented
Please clone this repo and make branches off of that in the future, forking makes it a little hard to check out and review your changes

2021-12-10 17:06 UTC, henry-js commented
Will close this and start again

2021-12-10 17:06 UTC, closed without merging